femas:
  agent:
    interceptors:
      # eureka
      - plugin:
          className: org.springframework.cloud.netflix.eureka.serviceregistry.EurekaServiceRegistry
          methodName: register
          interceptorClass: com.tencent.tsf.femas.agent.eureka.instrument.EurekaServiceRegistryInterceptor