// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PaasPolling.proto

package com.tencent.tsf.femas.config.grpc.paas;

public interface InitNamespaceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.InitNamespaceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string namespaceId = 1;</code>
   * @return The namespaceId.
   */
  java.lang.String getNamespaceId();
  /**
   * <code>string namespaceId = 1;</code>
   * @return The bytes for namespaceId.
   */
  com.google.protobuf.ByteString getNamespaceIdBytes();

  /**
   * <code>string registryAddress = 2;</code>
   * @return The registryAddress.
   */
  java.lang.String getRegistryAddress();
  /**
   * <code>string registryAddress = 2;</code>
   * @return The bytes for registryAddress.
   */
  com.google.protobuf.ByteString getRegistryAddressBytes();
}
