// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PaasPolling.proto

package com.tencent.tsf.femas.config.grpc.paas;

import com.tencent.tsf.femas.common.util.StringUtils;

/**
 * Protobuf type {@code grpc.InitNamespaceRequest}
 */
public final class InitNamespaceRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:grpc.InitNamespaceRequest)
    InitNamespaceRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use InitNamespaceRequest.newBuilder() to construct.
  private InitNamespaceRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private InitNamespaceRequest() {
    namespaceId_ = "";
    registryAddress_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new InitNamespaceRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private InitNamespaceRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            namespaceId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            registryAddress_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.tencent.tsf.femas.config.grpc.paas.LongPollingServer.internal_static_grpc_InitNamespaceRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.tencent.tsf.femas.config.grpc.paas.LongPollingServer.internal_static_grpc_InitNamespaceRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.tencent.tsf.femas.config.grpc.paas.InitNamespaceRequest.class, com.tencent.tsf.femas.config.grpc.paas.InitNamespaceRequest.Builder.class);
  }

  public static final int NAMESPACEID_FIELD_NUMBER = 1;
  private volatile java.lang.Object namespaceId_;
  /**
   * <code>string namespaceId = 1;</code>
   * @return The namespaceId.
   */
  @java.lang.Override
  public java.lang.String getNamespaceId() {
    java.lang.Object ref = namespaceId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      namespaceId_ = s;
      return s;
    }
  }
  /**
   * <code>string namespaceId = 1;</code>
   * @return The bytes for namespaceId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNamespaceIdBytes() {
    java.lang.Object ref = namespaceId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      namespaceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REGISTRYADDRESS_FIELD_NUMBER = 2;
  private volatile java.lang.Object registryAddress_;
  /**
   * <code>string registryAddress = 2;</code>
   * @return The registryAddress.
   */
  @java.lang.Override
  public java.lang.String getRegistryAddress() {
    java.lang.Object ref = registryAddress_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      registryAddress_ = s;
      return s;
    }
  }
  /**
   * <code>string registryAddress = 2;</code>
   * @return The bytes for registryAddress.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRegistryAddressBytes() {
    java.lang.Object ref = registryAddress_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      registryAddress_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) {
      return true;
    }
    if (isInitialized == 0) {
      return false;
    }

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (StringUtils.isNotBlank((String)namespaceId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, namespaceId_);
    }
    if (StringUtils.isNotBlank((String)registryAddress_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, registryAddress_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) {
      return size;
    }

    size = 0;
    if (StringUtils.isNotBlank((String)namespaceId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, namespaceId_);
    }
    if (StringUtils.isNotBlank((String)registryAddress_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, registryAddress_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.tencent.tsf.femas.config.grpc.paas.InitNamespaceRequest)) {
      return super.equals(obj);
    }
    com.tencent.tsf.femas.config.grpc.paas.InitNamespaceRequest other = (com.tencent.tsf.femas.config.grpc.paas.InitNamespaceRequest) obj;

    if (!getNamespaceId().equals(other.getNamespaceId())) {
      return false;
    }
    if (!getRegistryAddress().equals(other.getRegistryAddress())) {
      return false;
    }
    if (!unknownFields.equals(other.unknownFields)) {
      return false;
    }
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAMESPACEID_FIELD_NUMBER;
    hash = (53 * hash) + getNamespaceId().hashCode();
    hash = (37 * hash) + REGISTRYADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + getRegistryAddress().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.tencent.tsf.femas.config.grpc.paas.InitNamespaceRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tencent.tsf.femas.config.grpc.paas.InitNamespaceRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tencent.tsf.femas.config.grpc.paas.InitNamespaceRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tencent.tsf.femas.config.grpc.paas.InitNamespaceRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tencent.tsf.femas.config.grpc.paas.InitNamespaceRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tencent.tsf.femas.config.grpc.paas.InitNamespaceRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tencent.tsf.femas.config.grpc.paas.InitNamespaceRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tencent.tsf.femas.config.grpc.paas.InitNamespaceRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tencent.tsf.femas.config.grpc.paas.InitNamespaceRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.tencent.tsf.femas.config.grpc.paas.InitNamespaceRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tencent.tsf.femas.config.grpc.paas.InitNamespaceRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tencent.tsf.femas.config.grpc.paas.InitNamespaceRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.tencent.tsf.femas.config.grpc.paas.InitNamespaceRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code grpc.InitNamespaceRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:grpc.InitNamespaceRequest)
      com.tencent.tsf.femas.config.grpc.paas.InitNamespaceRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tencent.tsf.femas.config.grpc.paas.LongPollingServer.internal_static_grpc_InitNamespaceRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tencent.tsf.femas.config.grpc.paas.LongPollingServer.internal_static_grpc_InitNamespaceRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tencent.tsf.femas.config.grpc.paas.InitNamespaceRequest.class, com.tencent.tsf.femas.config.grpc.paas.InitNamespaceRequest.Builder.class);
    }

    // Construct using com.tencent.tsf.femas.config.grpc.paas.InitNamespaceRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      namespaceId_ = "";

      registryAddress_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.tencent.tsf.femas.config.grpc.paas.LongPollingServer.internal_static_grpc_InitNamespaceRequest_descriptor;
    }

    @java.lang.Override
    public com.tencent.tsf.femas.config.grpc.paas.InitNamespaceRequest getDefaultInstanceForType() {
      return com.tencent.tsf.femas.config.grpc.paas.InitNamespaceRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.tencent.tsf.femas.config.grpc.paas.InitNamespaceRequest build() {
      com.tencent.tsf.femas.config.grpc.paas.InitNamespaceRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.tencent.tsf.femas.config.grpc.paas.InitNamespaceRequest buildPartial() {
      com.tencent.tsf.femas.config.grpc.paas.InitNamespaceRequest result = new com.tencent.tsf.femas.config.grpc.paas.InitNamespaceRequest(this);
      result.namespaceId_ = namespaceId_;
      result.registryAddress_ = registryAddress_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.tencent.tsf.femas.config.grpc.paas.InitNamespaceRequest) {
        return mergeFrom((com.tencent.tsf.femas.config.grpc.paas.InitNamespaceRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.tencent.tsf.femas.config.grpc.paas.InitNamespaceRequest other) {
      if (other == com.tencent.tsf.femas.config.grpc.paas.InitNamespaceRequest.getDefaultInstance()) return this;
      if (!other.getNamespaceId().isEmpty()) {
        namespaceId_ = other.namespaceId_;
        onChanged();
      }
      if (!other.getRegistryAddress().isEmpty()) {
        registryAddress_ = other.registryAddress_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.tencent.tsf.femas.config.grpc.paas.InitNamespaceRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.tencent.tsf.femas.config.grpc.paas.InitNamespaceRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object namespaceId_ = "";
    /**
     * <code>string namespaceId = 1;</code>
     * @return The namespaceId.
     */
    public java.lang.String getNamespaceId() {
      java.lang.Object ref = namespaceId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        namespaceId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string namespaceId = 1;</code>
     * @return The bytes for namespaceId.
     */
    @Override
    public com.google.protobuf.ByteString
        getNamespaceIdBytes() {
      java.lang.Object ref = namespaceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        namespaceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string namespaceId = 1;</code>
     * @param value The namespaceId to set.
     * @return This builder for chaining.
     */
    public Builder setNamespaceId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      namespaceId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string namespaceId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearNamespaceId() {
      
      namespaceId_ = getDefaultInstance().getNamespaceId();
      onChanged();
      return this;
    }
    /**
     * <code>string namespaceId = 1;</code>
     * @param value The bytes for namespaceId to set.
     * @return This builder for chaining.
     */
    public Builder setNamespaceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      namespaceId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object registryAddress_ = "";
    /**
     * <code>string registryAddress = 2;</code>
     * @return The registryAddress.
     */
    @Override
    public java.lang.String getRegistryAddress() {
      java.lang.Object ref = registryAddress_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        registryAddress_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string registryAddress = 2;</code>
     * @return The bytes for registryAddress.
     */
    @Override
    public com.google.protobuf.ByteString
        getRegistryAddressBytes() {
      java.lang.Object ref = registryAddress_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        registryAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string registryAddress = 2;</code>
     * @param value The registryAddress to set.
     * @return This builder for chaining.
     */
    public Builder setRegistryAddress(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      registryAddress_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string registryAddress = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearRegistryAddress() {
      
      registryAddress_ = getDefaultInstance().getRegistryAddress();
      onChanged();
      return this;
    }
    /**
     * <code>string registryAddress = 2;</code>
     * @param value The bytes for registryAddress to set.
     * @return This builder for chaining.
     */
    public Builder setRegistryAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      registryAddress_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:grpc.InitNamespaceRequest)
  }

  // @@protoc_insertion_point(class_scope:grpc.InitNamespaceRequest)
  private static final com.tencent.tsf.femas.config.grpc.paas.InitNamespaceRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.tencent.tsf.femas.config.grpc.paas.InitNamespaceRequest();
  }

  public static com.tencent.tsf.femas.config.grpc.paas.InitNamespaceRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<InitNamespaceRequest>
      PARSER = new com.google.protobuf.AbstractParser<InitNamespaceRequest>() {
    @java.lang.Override
    public InitNamespaceRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new InitNamespaceRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<InitNamespaceRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<InitNamespaceRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.tencent.tsf.femas.config.grpc.paas.InitNamespaceRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

