// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PaasPolling.proto

package com.tencent.tsf.femas.config.grpc.paas;

public final class LongPollingServer {
  private LongPollingServer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_SimpleParam_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_SimpleParam_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_ServiceApiRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_ServiceApiRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_ReportEventRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_ReportEventRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_InitNamespaceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_InitNamespaceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_PollingResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_PollingResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021PaasPolling.proto\022\004grpc\"\034\n\013SimpleParam" +
      "\022\r\n\005param\030\001 \001(\t\"g\n\021ServiceApiRequest\022\023\n\013" +
      "namespaceId\030\001 \001(\t\022\023\n\013serviceName\030\002 \001(\t\022\032" +
      "\n\022applicationVersion\030\003 \001(\t\022\014\n\004data\030\004 \001(\t" +
      "\"]\n\022ReportEventRequest\022\023\n\013namespaceId\030\001 " +
      "\001(\t\022\023\n\013serviceName\030\002 \001(\t\022\017\n\007eventId\030\003 \001(" +
      "\t\022\014\n\004data\030\004 \001(\t\"D\n\024InitNamespaceRequest\022" +
      "\023\n\013namespaceId\030\001 \001(\t\022\027\n\017registryAddress\030" +
      "\002 \001(\t\">\n\rPollingResult\022\014\n\004code\030\001 \001(\t\022\017\n\007" +
      "message\030\002 \001(\t\022\016\n\006result\030\003 \001(\t2\232\002\n\013PaasPo" +
      "lling\022<\n\020fetchBreakerRule\022\021.grpc.SimpleP" +
      "aram\032\023.grpc.PollingResult\"\000\022B\n\020reportSer" +
      "viceApi\022\027.grpc.ServiceApiRequest\032\023.grpc." +
      "PollingResult\"\000\022E\n\022reportServiceEvent\022\030." +
      "grpc.ReportEventRequest\032\023.grpc.PollingRe" +
      "sult\"\000\022B\n\rinitNamespace\022\032.grpc.InitNames" +
      "paceRequest\032\023.grpc.PollingResult\"\000B=\n&co" +
      "m.tencent.tsf.femas.config.grpc.paasB\021Lo" +
      "ngPollingServerP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_grpc_SimpleParam_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_grpc_SimpleParam_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_SimpleParam_descriptor,
        new java.lang.String[] { "Param", });
    internal_static_grpc_ServiceApiRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_grpc_ServiceApiRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_ServiceApiRequest_descriptor,
        new java.lang.String[] { "NamespaceId", "ServiceName", "ApplicationVersion", "Data", });
    internal_static_grpc_ReportEventRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_grpc_ReportEventRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_ReportEventRequest_descriptor,
        new java.lang.String[] { "NamespaceId", "ServiceName", "EventId", "Data", });
    internal_static_grpc_InitNamespaceRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_grpc_InitNamespaceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_InitNamespaceRequest_descriptor,
        new java.lang.String[] { "NamespaceId", "RegistryAddress", });
    internal_static_grpc_PollingResult_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_grpc_PollingResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_PollingResult_descriptor,
        new java.lang.String[] { "Code", "Message", "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
