// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PaasPolling.proto

package com.tencent.tsf.femas.config.grpc.paas;

public interface ReportEventRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.ReportEventRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string namespaceId = 1;</code>
   * @return The namespaceId.
   */
  java.lang.String getNamespaceId();
  /**
   * <code>string namespaceId = 1;</code>
   * @return The bytes for namespaceId.
   */
  com.google.protobuf.ByteString getNamespaceIdBytes();

  /**
   * <code>string serviceName = 2;</code>
   * @return The serviceName.
   */
  java.lang.String getServiceName();
  /**
   * <code>string serviceName = 2;</code>
   * @return The bytes for serviceName.
   */
  com.google.protobuf.ByteString getServiceNameBytes();

  /**
   * <code>string eventId = 3;</code>
   * @return The eventId.
   */
  java.lang.String getEventId();
  /**
   * <code>string eventId = 3;</code>
   * @return The bytes for eventId.
   */
  com.google.protobuf.ByteString getEventIdBytes();

  /**
   * <code>string data = 4;</code>
   * @return The data.
   */
  java.lang.String getData();
  /**
   * <code>string data = 4;</code>
   * @return The bytes for data.
   */
  com.google.protobuf.ByteString getDataBytes();
}
