// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PaasPolling.proto

package com.tencent.tsf.femas.config.grpc.paas;

public interface ServiceApiRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.ServiceApiRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string namespaceId = 1;</code>
   * @return The namespaceId.
   */
  java.lang.String getNamespaceId();
  /**
   * <code>string namespaceId = 1;</code>
   * @return The bytes for namespaceId.
   */
  com.google.protobuf.ByteString getNamespaceIdBytes();

  /**
   * <code>string serviceName = 2;</code>
   * @return The serviceName.
   */
  java.lang.String getServiceName();
  /**
   * <code>string serviceName = 2;</code>
   * @return The bytes for serviceName.
   */
  com.google.protobuf.ByteString getServiceNameBytes();

  /**
   * <code>string applicationVersion = 3;</code>
   * @return The applicationVersion.
   */
  java.lang.String getApplicationVersion();
  /**
   * <code>string applicationVersion = 3;</code>
   * @return The bytes for applicationVersion.
   */
  com.google.protobuf.ByteString getApplicationVersionBytes();

  /**
   * <code>string data = 4;</code>
   * @return The data.
   */
  java.lang.String getData();
  /**
   * <code>string data = 4;</code>
   * @return The bytes for data.
   */
  com.google.protobuf.ByteString getDataBytes();
}
