// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PaasPolling.proto

package com.tencent.tsf.femas.config.grpc.paas;

public interface SimpleParamOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.SimpleParam)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string param = 1;</code>
   * @return The param.
   */
  java.lang.String getParam();
  /**
   * <code>string param = 1;</code>
   * @return The bytes for param.
   */
  com.google.protobuf.ByteString  getParamBytes();
}
