femas:
  agent:
    interceptors:
      - plugin:
          className: com.alibaba.cloud.nacos.registry.NacosServiceRegistry
          methodName: register
          interceptorClass: com.tencent.tsf.femas.agent.nacos.instrument.NacosServiceRegistryInterceptor
      - plugin:
          className: com.alibaba.nacos.client.naming.utils.InitUtils
          methodName: initNamespaceForNaming
          methodType: static
          interceptorClass: com.tencent.tsf.femas.agent.nacos.instrument.NacosNameSpaceInitUtilsInterceptor